import GitHubLogo from "@/app/common/components/GitHubLogo";
import Image from "next/image";
import { TwitterLogo } from "@/app/common/components/twitterLogo";

const GoyaTwitterBot = () => {
  return (
    <main className="flex min-h-screen flex-col items-center px-24">
      <section className="min-w-[70vw] md:pt-14 pt-24 font-semibold">
        <h1 className="text-2xl">Goya Twitter/X bot</h1>
        <div className="my-6 w-[75vw] h-0.5 border-t-0 bg-charcoal/10" />
      </section>

      <section className="flex flex-col md:flex-row w-[70vw] pt-6">
        <div className="w-[95%] md:w-[50%] mb-8 md:mb-24">
          <div className="flex flex-col md:flex-row mb-8">
            <div className="w-24">
              <h3 className="text-xl font-bold">Tech</h3>
            </div>
            <ul className="hidden md:block mt-1">
              <li>OpenAI</li>
              <li>AWS</li>
              <li>AWS CDK</li>
              <li>Lambda</li>
              <li>Cloud Formation</li>
              <li>S3</li>
              <li>EventBridge</li>
              <li>DynamoDB</li>
              <li>SecretsManger</li>
            </ul>
          </div>

          <div className="flex flex-col md:flex-row mb-8">
            <div className="w-24">
              <h3 className="text-xl font-bold">Year</h3>
            </div>
            <div className="flex flex-col md:flex-row">
              <p className="md:self-end">2023</p>
            </div>
          </div>

          <div className="flex flex-col md:flex-row">
            <div className="w-24">
              <h3 className="text-xl font-bold">Status</h3>
            </div>
            <div className="flex">
              <p className="self-end">Active - 2023</p>
            </div>
          </div>
        </div>

        <div className="w-[70vw] md:w-[60vw]">
          <h3 className="text-xl font-bold">Description</h3>
          <p className="md:mt-4 ">
            Goya bot is a an automated Twitter/X bot that makes a post once a a
            day on the works of Francisco Goya. It is built with AWS using Node,
            Typescript and OpenAI. It has an event driven architecture. An
            EventBridge routine is run each morning triggering lambdas that
            generate a new tweet with content generated by AI related to works
            of Goya. S3 is used as storage for the images and dynamoDB for the
            persistent state of the app. The tweet is then posted to Twitter
            using the Twitter v2 API.
          </p>
          <p className="mt-4">
            The app is driven by a Cron job operating once a day at 6am UTC.
          </p>
        </div>
      </section>

      <div className="w-[70vw] mt-8 md:mt-0 pb-6">
        <h3 className="text-xl font-bold">Previews</h3>
      </div>
      <section className="w-[95vw] grid md:grid-cols-2 md:gap-8 sm:grid-cols-1 gap-x-2 gap-y-4 sm:px-2 md:w-[70vw]">
        <div className="col-span-2 w-[100%] h-[27vh] border-2 border-charcoal/10 rounded-md border-solid relative">
          <Image
            src="/images/goya/goya-twitter-banner.png"
            alt="Twitter profile header"
            fill
          />
        </div>
        <div className="h-[50vh] border-2 border-charcoal/10 rounded-md border-solid relative">
          <Image
            src="/images/goya/goya-twitter-tweet-one.png"
            alt="Twitter tweet snapshot"
            fill
          />
        </div>
        <div className="h-[50vh] border-2 border-charcoal/10 rounded-md border-solid relative">
          <Image
            src="/images/goya/goya-twitter-tweet-two.png"
            alt="Twitter tweet snapshot"
            fill
          />
        </div>
      </section>

      <section className="w-[70vw] md:pt-6 pt-14">
        <h3 className="text-xl font-bold mb-2">Design</h3>
        <p>
          The architecture was designed to be cost effective as possible and
          utilizes generous offers from AWS that makes this small app run for
          very few pence! I will add a landing page in the coming weeks and will
          host it on S3.
        </p>
      </section>

      <section className="w-[70vw] md:pt-6 pt-14">
        <h3 className="text-xl font-bold mb-2">Extra info</h3>
        <p>
          The integration with the Twitter v2 api comes from the npm package{" "}
          <a
            target="_blank"
            rel="noreferrer noopener"
            href="https://www.npmjs.com/package/twitter-api-v2"
            className="text-terracotta font-medium hover:underline underline-offset-4"
          >
            twitter-api-v2
          </a>
        </p>
      </section>

      <section className="w-[70vw] md:pt-6 pt-14 pb-8">
        <h3 className="text-xl font-bold mb-2">Links</h3>
        <div className="flex">
          <p className="hover:font-bold hover:underline">
            <a
              rel="noreferrer"
              target="_blank"
              href="https://github.com/DermotBoyle/goya_bot"
            >
              <GitHubLogo />
            </a>
          </p>
          <p className="hover:font-bold hover:underline text-sm pl-4 self-center">
            <a
              rel="noreferrer"
              target="_blank"
              href="https://twitter.com/goya_explained"
            >
              <TwitterLogo />
            </a>
          </p>
        </div>
      </section>
    </main>
  );
};

export default GoyaTwitterBot;
